import { NextResponse } from "next/server";
import { readFile } from "fs/promises";
import { join } from "path";

export async function GET() {
  try {
    // Read the .env file from the root directory
    const envPath = join(process.cwd(), ".env");

    try {
      const envContent = await readFile(envPath, "utf8");

      return new NextResponse(envContent, {
        status: 200,
        headers: {
          "Content-Type": "text/plain",
          "Content-Disposition": "attachment; filename=.env",
        },
      });
    } catch {
      // If .env file doesn't exist, return a default template
      const defaultEnvContent = `# Better Auth Environment Variables
# Generated by Better Auth Pulse Studio

DATABASE_URL=  # Database connection string - REQUIRED
BETTER_AUTH_SECRET=  # Secret key for Better Auth (generate with: openssl rand -base64 32) - REQUIRED
NEXT_PUBLIC_APP_URL=  # Your app URL (e.g., http://localhost:3000) - REQUIRED

# OAuth Provider Credentials
# Add your OAuth provider credentials here
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=

# Email Configuration
RESEND_API_KEY=  # Resend API key for sending emails - OPTIONAL
FROM_EMAIL=  # From email address - OPTIONAL

# Plugin Configuration
POLAR_API_KEY=  # Polar API key - OPTIONAL
POLAR_WEBHOOK_SECRET=  # Polar webhook secret - OPTIONAL
`;

      return new NextResponse(defaultEnvContent, {
        status: 200,
        headers: {
          "Content-Type": "text/plain",
          "Content-Disposition": "attachment; filename=.env",
        },
      });
    }
  } catch (error) {
    console.error("Error reading .env file:", error);
    return NextResponse.json(
      { error: "Failed to read .env file" },
      { status: 500 }
    );
  }
}
